### ISSUE TITLE
Package not easily found on package.elm-lang.org

### ISSUE THREAD

**Issue by francescortiz** [newmana/chroma-elm#3]
It would be great if you added a descriptive sentence with the keyword color to the README, because now looking for `color` in package.elm-lang.org doesn't show `chroma-elm` as a result. I had totally missed this package thought I did look for color manipulation a few times.

Awesome package! Thanks!

**Comment by newmana** [comment]
Thank you for the suggestion.  I've tried to improve the description as best I could.

**Comment by francescortiz** [comment]
Awesome!
